<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.19
 *   protoc               — v6.33.5
 * Source: tests/protos/topic_v1.proto
 */

declare(strict_types=1);

namespace Topic\Api\V1;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class Event
{
    public function __construct(
        #[Reflection\Field(1, Reflection\StringT::T)]
        public string $type = '',
        #[Reflection\Field(2, Reflection\StringT::T)]
        public string $payload = '',
        #[Reflection\Field(3, new Reflection\ObjectT(\Google\Protobuf\Timestamp::class))]
        public ?\Google\Protobuf\Timestamp $ts = null,
    ) {}
}
