<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.19
 *   protoc               — v6.33.5
 * Source: tests/protos/topic_v1.proto
 */

declare(strict_types=1);

namespace Topic\Api\V1;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class SubscribeRequest
{
    public function __construct(
        #[Reflection\Field(1, Reflection\StringT::T)]
        public string $topic = '',
    ) {}
}
