<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.10
 *   protoc               — v6.33.5
 * Source: tests/protos/topic_v1.proto
 */

declare(strict_types=1);

namespace Topic\Api\V1;

use Override;
use Thesis\Protobuf\Pool;

/**
 * @api
 */
final readonly class TestsProtosTopicV1DescriptorRegistry implements Pool\Registrar
{
    private const string DESCRIPTOR_BUFFER = 'Cht0ZXN0cy9wcm90b3MvdG9waWNfdjEucHJvdG8SDHRvcGljLmFwaS52MRofZ29vZ2xlL3Byb3RvYnVmL3RpbWVzdGFtcC5wcm90byIoChBTdWJzY3JpYmVSZXF1ZXN0EhQKBXRvcGljGAEgASgJUgV0b3BpYyJhCgVFdmVudBISCgR0eXBlGAEgASgJUgR0eXBlEhgKB3BheWxvYWQYAiABKAlSB3BheWxvYWQSKgoCdHMYAyABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wUgJ0czJSCgxUb3BpY1NlcnZpY2USQgoJU3Vic2NyaWJlEh4udG9waWMuYXBpLnYxLlN1YnNjcmliZVJlcXVlc3QaEy50b3BpYy5hcGkudjEuRXZlbnQwAUqQAwoGEgQAABIBCggKAQwSAwAAEgoJCgIDABIDAgApCggKAQISAwQAFQoKCgIEABIEBgAIAQoKCgMEAAESAwYIGAoLCgQEAAIAEgMHBBUKDAoFBAACAAUSAwcECgoMCgUEAAIAARIDBwsQCgwKBQQAAgADEgMHExQKCgoCBAESBAoADgEKCgoDBAEBEgMKCA0KCwoEBAECABIDCwQUCgwKBQQBAgAFEgMLBAoKDAoFBAECAAESAwsLDwoMCgUEAQIAAxIDCxITCgsKBAQBAgESAwwEFwoMCgUEAQIBBRIDDAQKCgwKBQQBAgEBEgMMCxIKDAoFBAECAQMSAwwVFgoLCgQEAQICEgMNBCUKDAoFBAECAgYSAw0EHQoMCgUEAQICARIDDR4gCgwKBQQBAgIDEgMNIyQKCgoCBgASBBAAEgEKCgoDBgABEgMQCBQKCwoEBgACABIDEQQ7CgwKBQYAAgABEgMRCBEKDAoFBgACAAISAxESIgoMCgUGAAIABhIDES0zCgwKBQYAAgADEgMRNDliBnByb3RvMw==';

    #[Override]
    public function register(Pool\Registry $pool): void
    {
        $pool->add(Pool\Descriptor::base64(self::DESCRIPTOR_BUFFER), [
            'topic.api.v1.SubscribeRequest' => new Pool\MessageMetadata(\Topic\Api\V1\SubscribeRequest::class),
            'topic.api.v1.Event' => new Pool\MessageMetadata(\Topic\Api\V1\Event::class),
        ]);
    }
}
