<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.20
 *   protoc               — v6.33.5
 * Source: tests/protos/topic_v1.proto
 */

declare(strict_types=1);

namespace Topic\Api\V1;

use Override;
use Thesis\Protobuf\Registry;
use Thesis\Protobuf\Registry\File;

/**
 * @api
 */
final readonly class TestsProtosTopicV1DescriptorRegistry implements Registry\Registrar
{
    private const string DESCRIPTOR_BUFFER = 'Cht0ZXN0cy9wcm90b3MvdG9waWNfdjEucHJvdG8SDHRvcGljLmFwaS52MRofZ29vZ2xlL3Byb3RvYnVmL3RpbWVzdGFtcC5wcm90byIoChBTdWJzY3JpYmVSZXF1ZXN0EhQKBXRvcGljGAEgASgJUgV0b3BpYyJhCgVFdmVudBISCgR0eXBlGAEgASgJUgR0eXBlEhgKB3BheWxvYWQYAiABKAlSB3BheWxvYWQSKgoCdHMYAyABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wUgJ0czJSCgxUb3BpY1NlcnZpY2USQgoJU3Vic2NyaWJlEh4udG9waWMuYXBpLnYxLlN1YnNjcmliZVJlcXVlc3QaEy50b3BpYy5hcGkudjEuRXZlbnQwAUqQAwoGEgQAABIBCggKAQwSAwAAEgoJCgIDABIDAgApCggKAQISAwQAFQoKCgIEABIEBgAIAQoKCgMEAAESAwYIGAoLCgQEAAIAEgMHBBUKDAoFBAACAAUSAwcECgoMCgUEAAIAARIDBwsQCgwKBQQAAgADEgMHExQKCgoCBAESBAoADgEKCgoDBAEBEgMKCA0KCwoEBAECABIDCwQUCgwKBQQBAgAFEgMLBAoKDAoFBAECAAESAwsLDwoMCgUEAQIAAxIDCxITCgsKBAQBAgESAwwEFwoMCgUEAQIBBRIDDAQKCgwKBQQBAgEBEgMMCxIKDAoFBAECAQMSAwwVFgoLCgQEAQICEgMNBCUKDAoFBAECAgYSAw0EHQoMCgUEAQICARIDDR4gCgwKBQQBAgIDEgMNIyQKCgoCBgASBBAAEgEKCgoDBgABEgMQCBQKCwoEBgACABIDEQQ7CgwKBQYAAgABEgMRCBEKDAoFBgACAAISAxESIgoMCgUGAAIABhIDES0zCgwKBQYAAgADEgMRNDliBnByb3RvMw==';

    #[Override]
    public function register(Registry\Pool $pool): void
    {
        $pool->add(Registry\Descriptor::base64(self::DESCRIPTOR_BUFFER), new File(
            name: 'tests/protos/topic_v1.proto',
            dependencies: [
                'google/protobuf/timestamp.proto',
            ],
            messages: [
                new File\MessageDescriptor('topic.api.v1.SubscribeRequest', \Topic\Api\V1\SubscribeRequest::class),
                new File\MessageDescriptor('topic.api.v1.Event', \Topic\Api\V1\Event::class),
            ],
            services: [
                new File\ServiceDescriptor(
                    name: 'topic.api.v1.TopicService',
                    methods: [
                        new File\MethodDescriptor('Subscribe', false, true),
                    ],
                ),
            ],
        ));
    }
}
