<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.7
 *   protoc               — v6.33.5
 * Source: tests/protos/topic_v1.proto
 */

declare(strict_types=1);

namespace Topic\Api\V1;

use Amp\Cancellation;
use Thesis\Grpc\Metadata;
use Thesis\Grpc\Server;

/**
 * @api
 */
interface TopicServiceServer
{
    /**
     * @param Server\ServerStreamChannel<\Topic\Api\V1\SubscribeRequest, \Topic\Api\V1\Event> $stream
     */
    public function subscribe(
        \Topic\Api\V1\SubscribeRequest $request,
        Server\ServerStreamChannel $stream,
        Metadata $md,
        Cancellation $cancellation,
    ): void;
}
