<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.11
 *   protoc               — v6.33.5
 * Source: tests/protos/topic_v1.proto
 */

declare(strict_types=1);

namespace Topic\Api\V1;

use Amp\Cancellation;
use Thesis\Grpc\Metadata;

/**
 * @api
 */
interface TopicServiceServer
{
    /**
     * @return iterable<array-key, \Topic\Api\V1\Event>
     */
    public function subscribe(
        \Topic\Api\V1\SubscribeRequest $request,
        Metadata $md,
        Cancellation $cancellation,
    ): iterable;
}
