<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.10
 *   protoc               — v6.33.5
 * Source: tests/protos/topic_v1.proto
 */

declare(strict_types=1);

namespace Topic\Api\V1;

use Amp\Cancellation;
use Amp\NullCancellation;
use Thesis\Grpc\Client;
use Thesis\Grpc\Metadata;

/**
 * @api
 */
final readonly class TopicServiceClient
{
    public function __construct(
        private Client $client,
    ) {}

    /**
     * @return Client\ServerStreamChannel<\Topic\Api\V1\SubscribeRequest, \Topic\Api\V1\Event>
     */
    public function subscribe(
        \Topic\Api\V1\SubscribeRequest $request,
        Metadata $md = new Metadata(),
        Cancellation $cancellation = new NullCancellation(),
    ): Client\ServerStreamChannel {
        /** @var Client\Invoke<\Topic\Api\V1\SubscribeRequest, \Topic\Api\V1\Event> $invoke */
        $invoke = new Client\Invoke(
            method: '/topic.api.v1.TopicService/Subscribe',
            type: \Topic\Api\V1\Event::class,
        );

        $stream = $this->client->createStream(
            invoke: $invoke,
            md: $md,
            cancellation: $cancellation,
        );

        $stream->send($request);
        $stream->close();

        return new Client\ServerStreamChannel($stream);
    }
}
