<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.19
 *   protoc               — v6.33.5
 * Source: tests/protos/topic_v1.proto
 */

declare(strict_types=1);

namespace Topic\Api\V1;

use Override;
use Thesis\Grpc\Server;

/**
 * @api
 */
final readonly class TopicServiceServerRegistry implements Server\ServiceRegistry
{
    public function __construct(
        private \Topic\Api\V1\TopicServiceServer $server,
    ) {}

    #[Override]
    public function services(): iterable
    {
        yield new Server\Service('topic.api.v1.TopicService', [
            new Server\Rpc(
                new Server\Handle('Subscribe', \Topic\Api\V1\SubscribeRequest::class),
                new Server\ServerStreamHandler($this->server->subscribe(...)),
                Server\RpcType::ServerStream,
            ),
        ]);
    }
}
