<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.20
 *   protoc               — v6.33.5
 * Source: tests/protos/chat_v1.proto
 */

declare(strict_types=1);

namespace Chat\Api\V1;

use Amp\Cancellation;
use Amp\NullCancellation;
use Thesis\Grpc\Client;
use Thesis\Grpc\Metadata;

/**
 * @api
 */
final readonly class MessengerServiceClient
{
    public function __construct(
        private Client $client,
    ) {}

    /**
     * @return Client\BidirectionalStreamChannel<\Chat\Api\V1\Message, \Chat\Api\V1\Message>
     */
    public function chat(
        Metadata $md = new Metadata(),
        Cancellation $cancellation = new NullCancellation(),
    ): Client\BidirectionalStreamChannel {
        /** @var Client\Invoke<\Chat\Api\V1\Message, \Chat\Api\V1\Message> $invoke */
        $invoke = new Client\Invoke(
            method: '/chat.api.v1.MessengerService/Chat',
            type: \Chat\Api\V1\Message::class,
        );

        $stream = $this->client->createStream(
            invoke: $invoke,
            md: $md,
            cancellation: $cancellation,
        );

        return new Client\BidirectionalStreamChannel($stream);
    }
}
