<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.7
 *   protoc               — v6.33.5
 * Source: tests/protos/chat_v1.proto
 */

declare(strict_types=1);

namespace Chat\Api\V1;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class Message
{
    public function __construct(
        #[Reflection\Field(1, Reflection\StringT::T)]
        public string $text = '',
    ) {}
}
