<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.11
 *   protoc               — v6.33.5
 * Source: tests/protos/chat_v1.proto
 */

declare(strict_types=1);

namespace Chat\Api\V1;

use Override;
use Thesis\Grpc\Server;

/**
 * @api
 */
final readonly class MessengerServiceServerRegistry implements Server\ServiceRegistry
{
    public function __construct(
        private \Chat\Api\V1\MessengerServiceServer $server,
    ) {}

    #[Override]
    public function services(): iterable
    {
        yield new Server\Service('chat.api.v1.MessengerService', [
            new Server\Rpc(
                new Server\Handle('Chat', \Chat\Api\V1\Message::class),
                new Server\BidirectionalStreamHandler($this->server->chat(...)),
                Server\RpcType::BidirectionalStream,
            ),
        ]);
    }
}
