<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.10
 *   protoc               — v6.33.5
 * Source: tests/protos/chat_v1.proto
 */

declare(strict_types=1);

namespace Chat\Api\V1;

use Amp\Cancellation;
use Thesis\Grpc\Metadata;
use Thesis\Grpc\Server;

/**
 * @api
 */
interface MessengerServiceServer
{
    /**
     * @param Server\BidirectionalStreamChannel<\Chat\Api\V1\Message, \Chat\Api\V1\Message> $stream
     */
    public function chat(Server\BidirectionalStreamChannel $stream, Metadata $md, Cancellation $cancellation): void;
}
