<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.19
 *   protoc               — v6.33.5
 * Source: tests/protos/chat_v1.proto
 */

declare(strict_types=1);

namespace Chat\Api\V1;

use Override;
use Thesis\Protobuf\Registry;
use Thesis\Protobuf\Registry\File;

/**
 * @api
 */
final readonly class TestsProtosChatV1DescriptorRegistry implements Registry\Registrar
{
    private const string DESCRIPTOR_BUFFER = 'Chp0ZXN0cy9wcm90b3MvY2hhdF92MS5wcm90bxILY2hhdC5hcGkudjEiHQoHTWVzc2FnZRISCgR0ZXh0GAEgASgJUgR0ZXh0MkoKEE1lc3NlbmdlclNlcnZpY2USNgoEQ2hhdBIULmNoYXQuYXBpLnYxLk1lc3NhZ2UaFC5jaGF0LmFwaS52MS5NZXNzYWdlKAEwAUrWAQoGEgQAAAoBCggKAQwSAwAAEgoICgECEgMCABQKCgoCBAASBAQABgEKCgoDBAABEgMECA8KCwoEBAACABIDBQQUCgwKBQQAAgAFEgMFBAoKDAoFBAACAAESAwULDwoMCgUEAAIAAxIDBRITCgoKAgYAEgQIAAoBCgoKAwYAARIDCAgYCgsKBAYAAgASAwkENgoMCgUGAAIAARIDCQgMCgwKBQYAAgAFEgMJDRMKDAoFBgACAAISAwkUGwoMCgUGAAIABhIDCSYsCgwKBQYAAgADEgMJLTRiBnByb3RvMw==';

    #[Override]
    public function register(Registry\Pool $pool): void
    {
        $pool->add(Registry\Descriptor::base64(self::DESCRIPTOR_BUFFER), new File(
            name: 'tests/protos/chat_v1.proto',
            messages: [
                new File\MessageDescriptor('chat.api.v1.Message', \Chat\Api\V1\Message::class),
            ],
            services: [
                new File\ServiceDescriptor(
                    name: 'chat.api.v1.MessengerService',
                    methods: [
                        new File\MethodDescriptor('Chat', true, true),
                    ],
                ),
            ],
        ));
    }
}
