<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.7
 *   protoc               — v6.33.5
 * Source: tests/protos/chat_v1.proto
 */

declare(strict_types=1);

namespace Chat\Api\V1;

use Override;
use Thesis\Protobuf\Pool;

/**
 * @api
 */
final readonly class TestsProtosChatV1DescriptorRegistry implements Pool\Registrar
{
    private const string DESCRIPTOR_BUFFER = 'Chp0ZXN0cy9wcm90b3MvY2hhdF92MS5wcm90bxILY2hhdC5hcGkudjEiHQoHTWVzc2FnZRISCgR0ZXh0GAEgASgJUgR0ZXh0MkoKEE1lc3NlbmdlclNlcnZpY2USNgoEQ2hhdBIULmNoYXQuYXBpLnYxLk1lc3NhZ2UaFC5jaGF0LmFwaS52MS5NZXNzYWdlKAEwAUrWAQoGEgQAAAoBCggKAQwSAwAAEgoICgECEgMCABQKCgoCBAASBAQABgEKCgoDBAABEgMECA8KCwoEBAACABIDBQQUCgwKBQQAAgAFEgMFBAoKDAoFBAACAAESAwULDwoMCgUEAAIAAxIDBRITCgoKAgYAEgQIAAoBCgoKAwYAARIDCAgYCgsKBAYAAgASAwkENgoMCgUGAAIAARIDCQgMCgwKBQYAAgAFEgMJDRMKDAoFBgACAAISAwkUGwoMCgUGAAIABhIDCSYsCgwKBQYAAgADEgMJLTRiBnByb3RvMw==';

    #[Override]
    public function register(Pool\Registry $pool): void
    {
        $pool->add(Pool\Descriptor::base64(self::DESCRIPTOR_BUFFER), [
            'chat.api.v1.Message' => new Pool\MessageMetadata(\Chat\Api\V1\Message::class),
        ]);
    }
}
