<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.7
 *   protoc               — v6.33.5
 * Source: tests/protos/echo_v1.proto
 */

declare(strict_types=1);

namespace Echos\Api\V1;

use Override;
use Thesis\Protobuf\Pool;

/**
 * @api
 */
final readonly class TestsProtosEchoV1DescriptorRegistry implements Pool\Registrar
{
    private const string DESCRIPTOR_BUFFER = 'Chp0ZXN0cy9wcm90b3MvZWNob192MS5wcm90bxIMZWNob3MuYXBpLnYxIikKC0VjaG9SZXF1ZXN0EhoKCHNlbnRlbmNlGAEgASgJUghzZW50ZW5jZSIqCgxFY2hvUmVzcG9uc2USGgoIc2VudGVuY2UYASABKAlSCHNlbnRlbmNlMkwKC0VjaG9TZXJ2aWNlEj0KBEVjaG8SGS5lY2hvcy5hcGkudjEuRWNob1JlcXVlc3QaGi5lY2hvcy5hcGkudjEuRWNob1Jlc3BvbnNlSokCCgYSBAAADgEKCAoBDBIDAAASCggKAQISAwIAFQoKCgIEABIEBAAGAQoKCgMEAAESAwQIEwoLCgQEAAIAEgMFBBgKDAoFBAACAAUSAwUECgoMCgUEAAIAARIDBQsTCgwKBQQAAgADEgMFFhcKCgoCBAESBAgACgEKCgoDBAEBEgMICBQKCwoEBAECABIDCQQYCgwKBQQBAgAFEgMJBAoKDAoFBAECAAESAwkLEwoMCgUEAQIAAxIDCRYXCgoKAgYAEgQMAA4BCgoKAwYAARIDDAgTCgsKBAYAAgASAw0EMQoMCgUGAAIAARIDDQgMCgwKBQYAAgACEgMNDRgKDAoFBgACAAMSAw0jL2IGcHJvdG8z';

    #[Override]
    public function register(Pool\Registry $pool): void
    {
        $pool->add(Pool\Descriptor::base64(self::DESCRIPTOR_BUFFER), [
            'echos.api.v1.EchoRequest' => new Pool\MessageMetadata(\Echos\Api\V1\EchoRequest::class),
            'echos.api.v1.EchoResponse' => new Pool\MessageMetadata(\Echos\Api\V1\EchoResponse::class),
        ]);
    }
}
