<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.2.0
 *   protoc               — v6.33.5
 * Source: tests/protos/file_v1.proto
 */

declare(strict_types=1);

namespace File\Api\V1;

use Override;
use Thesis\Grpc;
use Thesis\Grpc\Server;

/**
 * @api
 */
final readonly class FileServiceServerRegistry implements Server\ServiceRegistry
{
    public function __construct(
        private \File\Api\V1\FileServiceServer $server,
    ) {}

    #[Override]
    public function services(): iterable
    {
        yield new Server\Service('file.api.v1.FileService', [
            new Server\Rpc(
                handle: new Server\Handle('Upload', \File\Api\V1\Chunk::class),
                handler: new Server\ClientStreamHandler($this->server->upload(...)),
                type: Grpc\RpcType::ClientStream,
            ),
        ]);
    }
}
