<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.10
 *   protoc               — v6.33.5
 * Source: tests/protos/file_v1.proto
 */

declare(strict_types=1);

namespace File\Api\V1;

use Amp\Cancellation;
use Amp\NullCancellation;
use Thesis\Grpc\Client;
use Thesis\Grpc\Metadata;

/**
 * @api
 */
final readonly class FileServiceClient
{
    public function __construct(
        private Client $client,
    ) {}

    /**
     * @return Client\ClientStreamChannel<\File\Api\V1\Chunk, \File\Api\V1\FileInfo>
     */
    public function upload(
        Metadata $md = new Metadata(),
        Cancellation $cancellation = new NullCancellation(),
    ): Client\ClientStreamChannel {
        /** @var Client\Invoke<\File\Api\V1\Chunk, \File\Api\V1\FileInfo> $invoke */
        $invoke = new Client\Invoke(
            method: '/file.api.v1.FileService/Upload',
            type: \File\Api\V1\FileInfo::class,
        );

        $stream = $this->client->createStream(
            invoke: $invoke,
            md: $md,
            cancellation: $cancellation,
        );

        return new Client\ClientStreamChannel($stream);
    }
}
