<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.11
 *   protoc               — v6.33.5
 * Source: tests/protos/file_v1.proto
 */

declare(strict_types=1);

namespace File\Api\V1;

use Amp\Cancellation;
use Thesis\Grpc\Metadata;
use Thesis\Grpc\Server;

/**
 * @api
 */
interface FileServiceServer
{
    /**
     * @param Server\ClientStreamChannel<\File\Api\V1\Chunk, \File\Api\V1\FileInfo> $stream
     */
    public function upload(
        Server\ClientStreamChannel $stream,
        Metadata $md,
        Cancellation $cancellation,
    ): \File\Api\V1\FileInfo;
}
