<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.11
 *   protoc               — v6.33.5
 * Source: tests/protos/file_v1.proto
 */

declare(strict_types=1);

namespace File\Api\V1;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class FileInfo
{
    public function __construct(
        #[Reflection\Field(1, Reflection\Int32T::T)]
        public int $size = 0,
    ) {}
}
