<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.19
 *   protoc               — v6.33.5
 * Source: tests/protos/file_v1.proto
 */

declare(strict_types=1);

namespace File\Api\V1;

use Override;
use Thesis\Protobuf\Registry;
use Thesis\Protobuf\Registry\File;

/**
 * @api
 */
final readonly class TestsProtosFileV1DescriptorRegistry implements Registry\Registrar
{
    private const string DESCRIPTOR_BUFFER = 'Chp0ZXN0cy9wcm90b3MvZmlsZV92MS5wcm90bxILZmlsZS5hcGkudjEiIQoFQ2h1bmsSGAoHY29udGVudBgBIAEoDFIHY29udGVudCIeCghGaWxlSW5mbxISCgRzaXplGAEgASgFUgRzaXplMkQKC0ZpbGVTZXJ2aWNlEjUKBlVwbG9hZBISLmZpbGUuYXBpLnYxLkNodW5rGhUuZmlsZS5hcGkudjEuRmlsZUluZm8oAUqXAgoGEgQAAA4BCggKAQwSAwAAEgoICgECEgMCABQKCgoCBAASBAQABgEKCgoDBAABEgMECA0KCwoEBAACABIDBQQWCgwKBQQAAgAFEgMFBAkKDAoFBAACAAESAwUKEQoMCgUEAAIAAxIDBRQVCgoKAgQBEgQIAAoBCgoKAwQBARIDCAgQCgsKBAQBAgASAwkEEwoMCgUEAQIABRIDCQQJCgwKBQQBAgABEgMJCg4KDAoFBAECAAMSAwkREgoKCgIGABIEDAAOAQoKCgMGAAESAwwIEwoLCgQGAAIAEgMNBDEKDAoFBgACAAESAw0IDgoMCgUGAAIABRIDDRAWCgwKBQYAAgACEgMNFxwKDAoFBgACAAMSAw0nL2IGcHJvdG8z';

    #[Override]
    public function register(Registry\Pool $pool): void
    {
        $pool->add(Registry\Descriptor::base64(self::DESCRIPTOR_BUFFER), new File(
            name: 'tests/protos/file_v1.proto',
            messages: [
                new File\MessageDescriptor('file.api.v1.Chunk', \File\Api\V1\Chunk::class),
                new File\MessageDescriptor('file.api.v1.FileInfo', \File\Api\V1\FileInfo::class),
            ],
            services: [
                new File\ServiceDescriptor(
                    name: 'file.api.v1.FileService',
                    methods: [
                        new File\MethodDescriptor('Upload', true, false),
                    ],
                ),
            ],
        ));
    }
}
