<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.8
 *   protoc               — v6.33.5
 * Source: tests/protos/file_v1.proto
 */

declare(strict_types=1);

namespace File\Api\V1;

use Override;
use Thesis\Protobuf\Pool;

/**
 * @api
 */
final readonly class TestsProtosFileV1DescriptorRegistry implements Pool\Registrar
{
    private const string DESCRIPTOR_BUFFER = 'Chp0ZXN0cy9wcm90b3MvZmlsZV92MS5wcm90bxILZmlsZS5hcGkudjEiIQoFQ2h1bmsSGAoHY29udGVudBgBIAEoDFIHY29udGVudCIeCghGaWxlSW5mbxISCgRzaXplGAEgASgFUgRzaXplMkQKC0ZpbGVTZXJ2aWNlEjUKBlVwbG9hZBISLmZpbGUuYXBpLnYxLkNodW5rGhUuZmlsZS5hcGkudjEuRmlsZUluZm8oAUqXAgoGEgQAAA4BCggKAQwSAwAAEgoICgECEgMCABQKCgoCBAASBAQABgEKCgoDBAABEgMECA0KCwoEBAACABIDBQQWCgwKBQQAAgAFEgMFBAkKDAoFBAACAAESAwUKEQoMCgUEAAIAAxIDBRQVCgoKAgQBEgQIAAoBCgoKAwQBARIDCAgQCgsKBAQBAgASAwkEEwoMCgUEAQIABRIDCQQJCgwKBQQBAgABEgMJCg4KDAoFBAECAAMSAwkREgoKCgIGABIEDAAOAQoKCgMGAAESAwwIEwoLCgQGAAIAEgMNBDEKDAoFBgACAAESAw0IDgoMCgUGAAIABRIDDRAWCgwKBQYAAgACEgMNFxwKDAoFBgACAAMSAw0nL2IGcHJvdG8z';

    #[Override]
    public function register(Pool\Registry $pool): void
    {
        $pool->add(Pool\Descriptor::base64(self::DESCRIPTOR_BUFFER), [
            'file.api.v1.Chunk' => new Pool\MessageMetadata(\File\Api\V1\Chunk::class),
            'file.api.v1.FileInfo' => new Pool\MessageMetadata(\File\Api\V1\FileInfo::class),
        ]);
    }
}
